version: 2
tags: ["documentation"]
accept_configuration:
  condition: property
  property: features
  not_contains_value: Disable

instructions:
  Build:
    - type: EnvironmentVariable
      variableName: BUILD_DOCUMENTATION
      variableValue: "1"
    - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"

  Test:
    - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
    - !include "{{qt/qtbase}}/coin_module_test_docs.yaml"
