[
    {
        "Action": {
            "type": "click",
            "data": [
                "LeftButton",
                "10 10"
            ]
        },
        "Events": [
            {
                "type": "MouseButtonPress",
                "object": "^QQuickView$",
                "position": "10 10",
                "data": "LeftButton"
            },
            {
                "type": "MouseButtonRelease",
                "object": "^QQuickView$",
                "position": "10 10",
                "data": "LeftButton"
            }
        ]
    },
    {
        "Action": {
            "type": "doubleclick",
            "data": [
                "LeftButton",
                "10 10"
            ]
        },
        "Events": [
            {
                "type": "MouseButtonPress",
                "object": "^QQuickView$",
                "position": "10 10",
                "data": "LeftButton",
                "events": 2
            },
            {
                "type": "MouseButtonDblClick",
                "object": "^QQuickView$",
                "position": "10 10",
                "data": "LeftButton"
            },
            {
                "type": "MouseButtonRelease",
                "object": "^QQuickView$",
                "position": "10 10",
                "data": "LeftButton",
                "events": 2
            }
        ]
    },
    {
        "Action": {
            "type": "click",
            "data": [
                "RightButton",
                "10 10"
            ]
        },
        "Events": [
            {
                "type": "MouseButtonPress",
                "object": "^QQuickView$",
                "position": "10 10",
                "data": "RightButton"
            },
            {
                "type": "ContextMenu",
                "object": "^QQuickView$",
                "position": "10 10"
            },
            {
                "type": "MouseButtonRelease",
                "object": "^QQuickView$",
                "position": "10 10",
                "data": "RightButton"
            }
        ]
    }
]
