# Copyright (C) 2023 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial

qt_extra_definition("QT_INSIGHT_TRACKER_VERSION_STR" "\"${PROJECT_VERSION}\"" PUBLIC)
qt_extra_definition("QT_INSIGHT_TRACKER_VERSION_MAJOR" ${PROJECT_VERSION_MAJOR} PUBLIC)
qt_extra_definition("QT_INSIGHT_TRACKER_VERSION_MINOR" ${PROJECT_VERSION_MINOR} PUBLIC)
qt_extra_definition("QT_INSIGHT_TRACKER_VERSION_PATCH" ${PROJECT_VERSION_PATCH} PUBLIC)
